version: "3.1"
services:
  insta:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_ENDPOINT=http://localhost:8080
    environment:
      - "ENV=development"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD="
      - "DATABASE_HOST=localhost"
      - "DATABASE_PORT=3306"
      - "DATABASE_DATABASE=dbktmira3"
      - "S3_BUCKET="
      - "S3_ACCESS_KEY="
      - "S3_SECRET_KEY="
      - "S3_ENDPOINT=https://fra1.digitaloceanspaces.com"
      - "S3_REGION=us-east-1"
    ports:
      - "8081:8080"