version: "3.1"
services:
  insta:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_ENDPOINT=http://localhost:8080
    environment:
      - "ENV=development"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD="
      - "DATABASE_HOST=localhost"
      - "DATABASE_PORT=3306"
      - "DATABASE_DATABASE=dbktmira3"
    ports:
      - "8081:8080"