POST http://localhost:8080/api/photos
Content-Type: application/json

{
  "path": "https://placekitten.com/1080/1080",
  "body": "this is my cat stevens"
}

###

GET http://localhost:8080/api/photos/1/comments
Content-Type: application/json